name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    # When you're ready to start creating releases,
    # set this "if" to "true"
    if: false
    steps:
      - uses: actions/checkout@v4
        with:
          path: latest
      - uses: obu-labs/vinaya-notes-module-releaser@main
        with:
          path: latest

